### ISSUE TITLE
Request: Asset Lookup

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#11]
it'd be handy to be able to reference Asset text. i'll happily volunteer to put the asset data together. 

the most polished version of this feature would include the icons, but that's inessential, and i'd probably want to figure out a way to extract them from the pdf en masse first.

![screencap of Xeno's mockup of the Asset lookup](https://cdn.discordapp.com/attachments/769276788097810472/771930087951695942/unknown.png)

**Comment by XenotropicDev** [comment]
This is actually complete now except a few special cases (Ironclad). I will close this and open a new issue for those special cases
