### ISSUE TITLE
Request: Glossary/add'l rules lookup

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#12]
concise explanation of rules elements not covered in the moves, with page references for easier lookup of more detailed information, whether as some sort of glossary or folded into the reference command.

Ironsworn's index and glossary are probably good places to start with deciding what email to compile.

challenges (w/r/t the rules data)
* 2000 character limit (use content from Lodestar, which is already concise for use as quick reference?)
* deciding on logical search terms, aliases
* structuring categories, relationships between rules terms (e.g. "see also...")

**Comment by XenotropicDev** [comment]
We'd also have to be careful about including too much of the rules from Delve/Starforged as they are not free resources.

**Comment by rsek** [comment]
re: delve, i actually checked this at one point to make sure my delve-based generators were on the level. from delve's credits page:

> The text of this work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license.

https://creativecommons.org/licenses/by-nc-sa/4.0/

> **Attribution** — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
> **NonCommercial** — You may not use the material for commercial purposes.
> **ShareAlike** — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
> **No additional restrictions** — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

so long as the proper attribution is included (presumably in the help message and readme) and the bot itself isn't a paid service, i think we should be in the clear. if you haven't already, you could set the repo's license to match: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository

more details on the NonCommercial license: https://wiki.creativecommons.org/wiki/NonCommercial_interpretation

> “NonCommercial means not primarily intended for or directed towards commercial advantage or monetary compensation.”

emphasis mine; my understanding (and, i mean, take it with a grain of salt, here - i'm a design school dropout, not a lawyer ;) ) is that donation/tip-jar-type situations (ko-fi and the like) are fine as well, should that be something you want to pursue. as long as the bot's delve content isn't conditional on payment, it's pretty clear it would fall outside of "commercial purposes".

starforged is a little murkier since it's playtest material, but Shawn's addressed it in the discord and i think we're in the clear:

https://discord.com/channels/751199753433514076/751265342541791402/751274139452571659

> **Can I create other games or custom materials based on the playtest?**
> You're welcome to hack away, but the playtest isn't under a creative commons license. I'd request that you not share materials which rely on Starforged elements beyond the Discord. Also keep in mind that things are likely to change, which may undermine your work. _The final release of Starforged in 2021 will utilize the same licensing model as original Ironsworn (Creative Commons with an SRD for commercial use)._ 

(emphasis mine)

> **Can I create digital tools/reference materials for Starforged**
> Yes, for your own use or for sharing with others here and in the main Ironsworn discord server. But please hold off sharing beyond the Discord servers, and keep in mind that things are likely to change.

potentially there'd be a conflict if, in the period before Starforged is released, the bot were to be posted outside of the discord (e.g. reddit or something) with starforged content. some approaches to mitigate this:

* two separate bots (at least until Starforged release). i think that would be detrimental to the bot's utility (i suspect a lot of people will play both games, or might want to use oracles from one game in the other sometimes), and i'm not sure what effects it would have on ease of maintenance and the like (i doubt it'd be making things *easier*, anyways)
* just don't post a *direct* link to the bot on reddit until Starforged is released in 2021. 
  * the down side: it wouldn't reach people who aren't on the IS/SF discord specifically but who would still find a discord bot useful. how many there are of those, i don't know, but it's not hard to imagine at least a handful of people using discord for their own small gaming groups or solo play who aren't engaged with the larger Ironsworn discord community
  * maybe if one posted *about* the bot (features etc) with a link directing people to the ironsworn discord bot-dev channel for more info; that way they're still getting filtered to the discord and getting the disclaimers etc.

**Comment by XenotropicDev** [comment]
If anyone is willing to do this it should be straight forward. It's mostly just choosing and organizing what rules elements should be included in the bot, and maybe adding some aliases/tags for them. I'd be willing to write any additional code needed to get this going.
