### ISSUE TITLE
Request: page numbers for Move reference

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#13]
presumably this would take the form of another property in the json file. 

i might word the embed's footer output as something like: "More information: p. ###", if only so the bot subtly reminds people there's much more detailed guidance available if needed; i figure if that can slip my mind when looking at a hardcopy move sheet, the same could happen to someone using the digital equivalent.

move *categories* might also warrant having page references. e.g. the combat category having a page reference number for the start of that section.

**Comment by rsek** [comment]
i've added page reference information for ironsworn moves, which is about as much as i can do since i doubt starforged page refs would be very helpful atm

**Comment by XenotropicDev** [comment]
Yeah, I don't think we can get starforged page numbers, but I think we might be able to two for one this with the source material property. I'm thinking something like:

```
            "Category": "Combat Moves",
            "Aliases": ["combat", "cm"],
            "Game": "Ironsworn",
            "Moves": [
                {
                    "Name": "Enter The Fray",
                    "Aliases": ["enter", "fray"],
                    "Text": "When **you enter into combat**....",
                    "Source": {
                        "Name": "Ironsworn Quick Reference",
                        "Page": "4",
                        "Url": null
                    }
                }
```

**Comment by XenotropicDev** [comment]
I switched the JSON that you added over to the format I posted above because it was easier for me to work with, and added support for displaying the source information to the rules reference command.
