### ISSUE TITLE
Request: Ironsworn settlement generation

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#15]
Ironsworn has much looser guidelines for settlement generation and fewer oracles to do it with, but i reckon something like:

* name
* location descriptor (i'd say 2 of them to start? this may just be because after starforged settlements, one descriptor doesn't seem like much!)
* settlement trouble (behind a spoiler tag)
* emoji reacts to add oracle results from: Location Descriptor, definitely; maybe even one for Oracle 4: Location (rationale: most settlements are going to be built near a feature of _some_ kind, be it a conveyance, body of water, natural resource, etc)

looking at this i start to wonder wonder what oracles could be backported from starforged (Authority in particular - maybe it'd work as an emoji react? hm), but that's definitely a nonstandard use and probably beyond the scope of this project, haha.

**Comment by XenotropicDev** [comment]
I thought about this, but I wasn't sure if this was something that would be worth while for how few rolls are needed. But it would be good for just to guide a player though creating a settlement with out having to remember a bunch of oracles.
