### ISSUE TITLE
Request: starforged creatures - emoji react to add a third First Look result

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#16]

**Comment by XenotropicDev** [comment]
It looks like there's a bug with the creatures where it always only shows two first looks, instead of adding a random 2-3. If I fix that is there still a desire to have it add 3rd/4th?

**Comment by rsek** [comment]
hmm, personally i'd only want to add oracle results up to the recommended number of rolls (so, have the option to add a 3rd, but not a 4th). but other people might want the option of adding them regardless of the recommended number.

an alternate implementation of the "1-3" and "2-3" oracles would be to roll the minimum number of results each time, and have emoji reacts to add results up to the maximum number.

i'm not sure which would be better or worse, honestly. maybe this is worth pitching to the discord to see how other folks feel about it?

**Comment by XenotropicDev** [comment]
Currently all the roll 1-3 style items pick a random number within the range, and use that to display the number of items. Populating them with the minimum number adding additional reactions wouldn't be a problem if that's the better way to handle it.
