### ISSUE TITLE
Starforged: planet generation interactive post unable to find PlanetTemplates.json

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#17]
<img width="1078" alt="Screen Shot 2020-10-31 at 12 01 06 AM" src="https://user-images.githubusercontent.com/5354757/97773363-466c6b00-1b0c-11eb-869c-c0cb6abdcd93.png">

same result for outlands/expanse regions, if it matters

**Comment by XenotropicDev** [comment]
It looks like i accidentally cut some files instead of copying them. Should be fixed now.
