### ISSUE TITLE
request: interactive posts for delve sites

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#21]
from the sounds of things this isn't in the immediate future, but here's some notes on the topic for when the time comes

steps to creating a delve site:
1) theme selection (with option to randomize)
<img width="161" alt="Screen Shot 2020-11-11 at 4 49 21 AM" src="https://user-images.githubusercontent.com/5354757/98813600-46584f00-23d9-11eb-85c0-e7c6e8a4e574.png">

2) domain selection (with option to randomize)
  * there's 12 of these, so it couldn't be done with number emoji alone. it might be possible to give domains representative emoji, though some are more difficult than others to represent
  * :headstone: and :polar_bear: exist on live, just not in the mockup tool
<img width="212" alt="Screen Shot 2020-11-11 at 4 50 11 AM" src="https://user-images.githubusercontent.com/5354757/98813651-6425b400-23d9-11eb-91e1-645ee7a37ff5.png">

3) site name generation as per the site name oracles, which is its own nested table with several components. (even without an interactive post, this might be worth making an embed for - maybe i should open a separate feature request for this specifically)
4) set site objective
5) set site rank (with option to randomize)

the delve worksheet includes the following information:
* site name
* objective
* theme
* domain
* site rank and progress, plus indicators (light/medium/dark boxes) for the Risk Zones optional rule (p. 54)
  * convey risk zone with text output of suggested risk level, based on site rank + delve progress?
* denizen matrix
  * this is pretty much ad hoc by the player, as-written; it's useful to have a place to write them down. ultimately it may be best left to the player. i'm not sure there's a way the bot can meaningfully assist in that sort of note-taking
  * that said... i suspect it would be helpful to many people to have the matrix filled out for them. there's a reason i spent so much time building a web-based denizen matrix generator for the purpose, haha. but i suspect that falls outside the scope of the bot.
  * as-is, that generator provides markdown output that can be copy-pasted into discord, and so long as the bot can roll d100 on its own, that's probably not too onerous?
  * if the ability for users to add custom oracles is implemented at some point, i could potentially add bot-friendly output to my matrix generator. i assume that's pretty far down the road, though.
    * that or wait for Perchance to get a proper API and just pull the results directly, but to my knowledge that's TBA and has been for a while 🤷 
* ~~a map/notes section~~ (pretty clearly outside the bot's scope)

<img width="443" alt="Screen Shot 2020-11-11 at 4 46 49 AM" src="https://user-images.githubusercontent.com/5354757/98813387-ebbef300-23d8-11eb-9452-2ddf993af878.png">

possible interactivity for delve site's embed once generated:
* standard progress functions (mark, roll, etc)
* roll Feature, 🍀 `:four_leaf_clover:` or 🔮 `:crystal_ball:` (though the latter might be better used on some other function, because it'd be a fun way to evoke the oracle theme)
* roll Danger, ⚠️ `:warning:`
* change Theme (occurs on certain Feature results) :regional_indicator_t: `:regional_indicator_t:`
  * how should this interact with double-theme sites?
* change Domain (occurs on certain Feature results) :regional_indicator_d: `:regional_indicator_d:`
  * how should this interact with double-domain sites?
* "If you are returning to a previously explored site, roll both challenge dice, take the lowest value, and clear that number of progress boxes." doing this manually wouldn't be the end of the world, though.

other concerns:
* double theme/double domain support (p. 69-70): optional rule and delve recommends against doubling up on both: e.g. ppl should have *either* 2 domains and 1 theme OR 1 domain and 2 themes)
  * probably not essential, but cool to have; even if it's not implemented until much later, may be worth keeping in mind when working out how single themes/domains function to save some grief on implementing doubles down the road

**Comment by XenotropicDev** [comment]
I don't see in the source book anywhere that explicitly says to change the theme/domain. The closest I can see is during the return to the site roll, but that only seems to indicate that things are vastly different than before, not that the theme/domain has changed.  Can someone point me in the right direction?

**Comment by rsek** [comment]
it's results 99 ("you transition to a new theme") and 00 ("you transition to a new domain") on the domain cards. it's described  in more detail on page 24:

> ## Transitioning into a New Theme or Domain
> A roll of 99 or 100 on the feature table triggers the introduction of a new theme or domain. When you encounter this result, choose a new theme or domain as appropriate to the situation. If in doubt, randomly draw a card or _Ask the Oracle_. You might find that the **Fortified** site is now **Infested**. You might stumble across a **Ruin** while navigating a **Tanglewood**. Discard the existing theme or domain and add the new one to your playscape. Keep all your existing progress. Then, envision what you encounter and how this transition manifests in your story. Your objective lies within.

**Comment by XenotropicDev** [comment]
I'm almost ready to close this. There's just changing themes/domains and returning to the site left. I'm not sure what I want to do about denizens yet, but it probably deserves its own GitHub issue.
