### ISSUE TITLE
meta: project-specific labels for github issues

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#23]
now that i'm flooding the issues tab 😅 it might be a good idea to add some labels. i'm certain the list below isn't exhaustive but it'd be a good start.

## game type
- Ironsworn
- Starforged

## module
- Oracle
- Rules Reference
- Action
- Initiative Tracker
- Progress Tracker
- Creature (would probably include ironsworn monstrosity?)
- NPC (for both systems)
- Planet
- Settlement (for both systems)
- Starship

## other
- Documentation

**Comment by XenotropicDev** [comment]
I added a few new labels, most Ironsworn, Starforged, and data issues for things like oracles and rules references. Is there value add in having a tag for each embed type?

**Comment by rsek** [comment]
i haven't really missed them not being there, so you're probably right.
