### ISSUE TITLE
request: scene challenge tracker

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#30]
ref: ironsworn, p. 234. 

* pretty much a progress track with the countdown track bolted on. the countdown track is 4 boxes, and unlike normal progress boxes it's either filled or not. it'd also be good to make the visually distinct from normal progress boxes. i reckon  :green_square: `:green_square:` and :negative_squared_cross_mark: `:negative_squared_cross_mark:` would work for that.
* scene challenges default to the Dangerous rank, and the text strongly recommends keeping them there unless there's a very compelling reason it should be otherwise. so i think it would make sense for the command to default to Dangerous in the absence of a specified rank
* emoji reacts as per progress tracks, with the addition of :negative_squared_cross_mark: `:negative_squared_cross_mark:` to mark the countdown track, and perhaps :green_square: `:green_square:` to remove it (to my knowledge there's no mechanic that removes marks from the countdown track, but it's probably a good idea to make it reversible in case someone misclicks)

<img width="660" alt="Screen Shot 2020-11-10 at 4 30 18 PM" src="https://user-images.githubusercontent.com/5354757/98750144-07db7980-2372-11eb-9ac9-432f2a2b9070.png">

**Comment by XenotropicDev** [comment]
Added in commit 94f25ad 

Closing.
