### ISSUE TITLE
improve !help output

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#31]
present state:
<img width="548" alt="Screen Shot 2020-11-10 at 6 23 38 PM" src="https://user-images.githubusercontent.com/5354757/98757651-dcf92180-2381-11eb-9736-a77c3457889c.png">
<img width="540" alt="Screen Shot 2020-11-10 at 6 39 00 PM" src="https://user-images.githubusercontent.com/5354757/98758600-03b85780-2384-11eb-8921-cc5590c629e3.png">

**Comment by XenotropicDev** [comment]
I changed the way that the help command works now. The main list looks a little better, but the lookup commands look a lot better now. If we need to revisit this we can open a new issue.
