### ISSUE TITLE
Player card/ship card: debility/impact tracker

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#34]
i remember this coming up, and it sounded like it wasn't in the cards for the time being; still, i reckon it's worth posting here to have a record of it in case it comes up again. feel free to label it wontfix or something. :)

perhaps unsurprisingly, i made a bunch of notes too.

Ironsworn, p. 36:
> * **Each marked debility** reduces your max momentum by 1.
> * If you have **one marked debility**, your momentum reset is +1 instead of +2.
> * If you have **more than one marked debility**, your momentum reset is 0.

* at its most basic this could be a field that shows the number of debilities someone has. probably left hidden unless debilities > 0, and it could be incremented/decremented similar to health/spirit/supply.
* a more elaborate version would display debilities by name (useful since debilities have different conditions for removal, and some are permanent)
* ideally the burn momentum react would take this into account, but even if it doesn't, i think there's value in having a place to note the fact that the debilities are present so the player is less likely to forget.
* each game has 8 standard debilities (Ironsworn: Wounded, Shaken, Unprepared, Encumbered, Maimed, Corrupted, Cursed, Tormented; Starforged: Wounded, Shaken, Unprepared, Disabled, Troubled, Doomed, Tormented, Indebted), plus a few assets (certain rituals, voidborn in SF, etc) that add their own unique debilities. 
  * since there's so many, it might just be simpler to do some sort of user input for the debility name than try to manage it with reacts... unless it was an interactive post or something, but that feels like overkill
* i like 💫 `:dizzy:`,  💔 `:broken_heart:`, and 🩸 `:drop_of_blood:` as candidates for the emoji react for managing debilities because they're more abstract/symbolic (and so they'd be the least obtrusive on the game's mood, if that makes sense? it's quite possible i'm overthinking this, ha), but there's no shortage of smiley-type emoji to depict various state of distress:  😵 😱 🤕 😬 ☹️ 😖 😣
  * if, mechanically speaking, debilities are working against momentum, then maybe this is an emoji that could be selected in opposition to whatever symbol we're using for momentum? heck, that could inform the choice of emoji for momentum should you want to change it
* starforged also has two debilities that can be attached to vehicles, so the ship card might need to track this, too. hm. even if it's not possible to have the player card check whether the vehicle in question has a debility that might effect the PC's momentum reset, it still helps to have a place to note it

**Comment by rsek** [comment]
update: in the current iteration of the rules, "debilities" are now termed "impacts"

**Comment by XenotropicDev** [comment]
Added support with inline replies for character cards. Ships should be soon.

**Comment by XenotropicDev** [comment]
Added ship debilities in 40eb89d. They can be tracked, but I'm not really sure how they interact within the game, so if they need additional features a new issue item can be opened for the specific features.
