### ISSUE TITLE
feature request from the discord: ironlands region reference

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#35]
<img width="1064" alt="Screen Shot 2020-11-13 at 9 46 52 AM" src="https://user-images.githubusercontent.com/5354757/99103938-2a99a800-2595-11eb-93db-1a355194850f.png">

**Comment by XenotropicDev** [comment]
I assume the single page references are the ones starting on page 113 of the core rule book?

**Comment by rsek** [comment]
yeah, those are the ones. some prototypes:

compact output (lodestar description + illustration only)
<img width="443" alt="Screen Shot 2020-11-13 at 10 21 09 AM" src="https://user-images.githubusercontent.com/5354757/99106962-f5dc1f80-2599-11eb-81ba-ff28080bdad4.png">

with features from Ironsworn: Core
<img width="446" alt="Screen Shot 2020-11-13 at 10 26 57 AM" src="https://user-images.githubusercontent.com/5354757/99107474-c548b580-259a-11eb-9397-cc496c7203aa.png">

long-form description + quest info
<img width="444" alt="Screen Shot 2020-11-13 at 10 21 28 AM" src="https://user-images.githubusercontent.com/5354757/99106991-012f4b00-259a-11eb-863b-fca90601d120.png">

the last one is pretty long. maybe the output is compact at first, and there's, say, an ℹ️ `:information_source:` react (and/or a command argument) to show the expanded info? similar principle could be applied to foe reference.

that or ditch the illustration, but aside from looking cool, i'd venture that the illustration is part of the information (just in a non-textual format), and so warrants consideration.

**Comment by XenotropicDev** [comment]
That should all be pretty straight forward. To save on space what if we used the thumbnail, then the user can click on it to make it bigger (like in the planet embeds). One potential down side to doing it this way is that discord mobile doesn't allow clicking on thumbnail images for some reason.

**Comment by rsek** [comment]
dang, if this is the same thumbnail bug, it looks like it's been outstanding for at least a year. guess i won't hold my breath for a timely fix, haha. https://support.discord.com/hc/en-us/community/posts/360053580892-Pictures-not-appearing-on-Android-10

anyways, i'll start putting some data together for that in a new branch and start grabbing the remaining region illustrations from the pdf.

**Comment by XenotropicDev** [comment]
This is the one I'm specifically referring to, and I wont be waiting for this one either.
https://support.discord.com/hc/en-us/community/posts/360042642271-Make-the-thumbnails-in-embeds-clickable-sometimes-we-want-to-see-better-a-profile-picture-and-clicking-the-embed-thumbnail-is-not-possible-on-mobile
