### ISSUE TITLE
cards: make rerolling duplicates the default behaviour

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#40]
my understanding is this is the designer intent of the oracle tables for planets, creatures, etc is to reroll duplicate results (i can dig up the discord messages from shawn to this effect if needed), so the default for cards (or perhaps just new/unset channels) should be to reroll duplicates.

**Comment by XenotropicDev** [comment]
This has actually been the default behavior in the bot for a while now, but there are some places where the entities still haven't implemented the check. If there are specific offenders that are particularly annoying for duplicate rolls post a new issue and I will fix them.

**Comment by rsek** [comment]
🤔 hmm. well, it may have changed in the mean time, but planet cards _did_ appear to be rolling duplicates (on a channel where reroll behaviour hadn't been set either way) as of Dec 14, which is what led me to open the issue in the first place:

<img width="592" alt="Screen Shot 2020-12-26 at 6 48 08 PM" src="https://user-images.githubusercontent.com/5354757/103162861-e7913e00-47aa-11eb-8ada-91569bb72383.png">
