### ISSUE TITLE
user-editable name fields for cards

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#41]
since exploration, discovery, and 'playing to find out' are a big part of the game, i think it'd be on-theme to have some way of setting the name of the npc/creature/ship/planet cards **after** they've been generated. this would also make it easier to locate them in the chat log using discord's search function, too, rather than approaching the search 'sideways' by trying to remember the contents of the fields or something. as well as covering those situations where there's a typo or maybe interference from autocorrect, haha.

✏️ `:pencil2:` is a pretty common metaphor for this sort of thing, so i think it'd be a solid choice for a react. i figure using that react could trigger the kind of text-based interaction currently used in Delve Site posts?

the 'dream'/expanded version of this feature would be being able to set/remove _any_ field after the fact, but that's probably a separate feature request.

**Comment by XenotropicDev** [comment]
I'm closing this as "Will not fix", but only because I think this will all be implemented with the upcoming "inline reply edit" commands or is already partially implemented with the `!EditField` command
