### ISSUE TITLE
legacy/xp tracking for Starforged PC embed

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#44]
<img width="624" alt="Screen Shot 2020-12-26 at 6 57 37 PM" src="https://user-images.githubusercontent.com/5354757/103162950-3b505700-47ac-11eb-8f34-09fa2f2899cf.png">

this is another "would be convenient but not immediately necessary" one, similar to #43 . it might also create enough differences between the IS/SF to justify having, say, an interactive post to ask which profile the user wants: ironsworn or starforged.

effectively legacy tracks are epic tracks; their rank doesn't need to be specified, which lets us cut down on some clutter:

<img width="352" alt="Screen Shot 2020-12-26 at 7 11 30 PM" src="https://user-images.githubusercontent.com/5354757/103163095-2c6aa400-47ae-11eb-9863-ad1c6914839b.png">

next to a fully generated planet card, that's not too bad, honestly.

as far as tracking XP...

the current SF rules give a flat 2xp per filled box on the legacy tracks (or 1xp per filled box for those PCs progressing past the initial 10 boxes).

<img width="527" alt="Screen Shot 2020-12-26 at 7 01 29 PM" src="https://user-images.githubusercontent.com/5354757/103162994-c6315180-47ac-11eb-9e10-6df415df1864.png">

from that, the PC's total earned XP could be derived and displayed, perhaps with an indicator of the XP they've spent, too.

<img width="293" alt="Screen Shot 2020-12-26 at 7 31 33 PM" src="https://user-images.githubusercontent.com/5354757/103163278-f975df80-47b0-11eb-8681-cba65183998a.png">

a tickbox labelled with +10 is used on the SF character sheet to indicate the track has been filled previously, so i've used something similar here. when rolling the challenge dice against a progress track that has exceeded 10, the action score is treated as though it were 10 (probably similar to the similar rule capping rolled action scores)

and all that seems straightforward, but actual _interacting_ with them is another problem.

if we were still marking 1-5 ticks on legacy tracks at once, it'd probably be fine just to have them use the single increment/decrement arrows used for other stats... but the current iteration of starforged (which reminds me, i gotta update the move/asset data to reflect it 😅 ) changes the amount of Legacy track progress marked per completed vow/bond/expedition:

<img width="286" alt="Screen Shot 2020-12-26 at 7 50 25 PM" src="https://user-images.githubusercontent.com/5354757/103163512-9afe3080-47b3-11eb-8f07-f18e689cd570.png">
<img width="283" alt="Screen Shot 2020-12-26 at 7 50 57 PM" src="https://user-images.githubusercontent.com/5354757/103163523-aea99700-47b3-11eb-9943-5e5515b5f3e3.png">
<img width="287" alt="Screen Shot 2020-12-26 at 7 53 18 PM" src="https://user-images.githubusercontent.com/5354757/103163557-021be500-47b4-11eb-841f-5663d137d829.png">

which means a total of 8/12 clicks on a resolving an Extreme/Epic task. oof.

admittedly, marking a legacy track is way less common than manipulating any other PC stat, and i'd wager that the majority of tasks are Troublesome, Dangerous, or Formidable, so it probably won't come up that often. and perhaps there's something satisfying about marking that many ticks at once when you finally overcome that Epic vow... but it could still really suck for ppl for whom repetitive clicking is difficult due to mobility concerns, or people who get distracted and lose count with some frequency (like me).

if that seems like it'd clutter things up with too many emoji reacts, it might be possible to make incrementing a legacy track an interactive post of some kind. perhaps a single emoji react that, when selected, prompts the user for the rank/number of ticks (there's a couple assets that add ticks - not progress - to an additional track, e.g. Diplomat). this level of interactivity would be onerous for adjusting something like health or momentum, but legacy tracks come up much less frequency.

**Comment by XenotropicDev** [comment]
This seems challenging, but possible. Mostly adding 3 more reactions seems like the most a user can remember without having to reference the manual every time they want to change something. 

Also we could use some inline reply commands to facilitate some of the less used features (spending XP, and adding lots of progress at once).

I will get started on this.
