### ISSUE TITLE
IS initiative tracker uses "Advantage"/"Disadvantage" instead of the game's terminology

### ISSUE THREAD

**Issue by rsek** [XenotropicDev/TheOracle#52]
noticed this when i was updating the readme. "Initiative"/"No Initiative" is a little awkward, but it's at least pretty clear what it is, and is probably the most compact way to describe it.

**Comment by XenotropicDev** [comment]
This has been added.

@rsek Just so you know almost all the strings that the bot uses are in resource files (resx extension - glorified xml text files) so if you want to change any of these feel free to change them and push them to the master branch.
