### ISSUE TITLE
Using !assetlist options returns object reference error if default game = Starforged

### ISSUE THREAD

**Issue by rewritable30** [XenotropicDev/TheOracle#65]
Looks like any use of filter/search options for !assetlist command returns an "Object reference not set to an instance of an object." error if default game for the channel is set to "Starforged". Options work OK for "Ironsworn" setting. 
How to reproduce:
1. !setdefaultgame starforged
2. !assetlist companion
![image](https://user-images.githubusercontent.com/68472411/145393945-c450ee2e-44e5-4d1d-b2dd-f2ea465e8463.png)

**Comment by XenotropicDev** [comment]
Thank you for the detailed write up. It looks like this was a latent issue with the recent conversion to DataForged's asset format. I just updated the bot to fix this issue, so happy gaming!
